configuration:
  projectName: configclient
server:
  port: 8000
message:
  greeting: Hello from the configuration!
cassandra:
  hostnames: "myHost"
  username: "myUser"
  password: "myPassword"

---
spring:
  profiles: dev
  dev:
    cassandra:
      hostname: "myDHost"
      userName: "myDUser"
      password: "myDpassword"
---
spring:
  profiles: test
  test:
    cassandra:
      hostname: "myTHost"
      userName: "myTUser"
      password: "myTpassword"