configuration:
  projectName: configclient
server:
  port: 8000
message:
  greeting: Hello from the configuration!
cassandra:
  hostnames: "myHost"
  username: "myUser"
  password: "myPassword"

---
spring:
  profiles: dev
cassandra:
  hostnames: "myDHost"
  username: "myDUser"
  password: "myDpassword"
---
spring:
  profiles: test
cassandra:
  hostnames: "myTHost"
  username: "myTUser"
  password: "myTpassword"

