server:
  port: 8000
cassandra:
  hostnames: "myOrHost"
  username: "myOrUser"
  #password: "myOrPassword"

---
spring:
  profiles: dev
cassandra:
  hostnames: "myDOrHost"
  username: "myDOrUser"
  password: "myDOrpassword"
---
spring:
  profiles: test
cassandra:
  hostnames: "myTOrHost"
  username: "myTOrUser"
  password: "myTOrpassword"
  #"{cipher}752AgAXT4EmTEx7iLTiCO0XEPvBpnFzZyx6o4jHfRSYBnYAPTjt8xfr3ekWW3tYgKICtGgv4BajlL3vAMxLEAhFVJ5ZxG1I1ZPGuJPZbJUjcODyiDCAoaLH3zSc8itU51gJBkF4xSocJOFMeyyaTgF/sD/C55mhSDybD5pU2uaXl51eeZmYfh6FOF/SkHLPwqvnL9+ubNbX34i52U+X1e9FfYQo2qyLLykJkNDoCsuZNXmCYXc0SDNoU92y1zsM/AVcKnd3LChgP4iEowrg0/cexEaDNqbzKYSAm1Ya+o1z0BUOUoXPt78+fkFj8wGG7d0i1XQxzHloOBbiuJ07AOzqJzDJreUQ4fqrA2I2f3BAgtqurT9x5DnsRS24hcf/ExyZgcYzJiN6L8Ot4Yb4eT+rCYJLUVfJyUZM6OFZKe13RiBqZg97V6M+q1L86uDnT64msaQFR71cSi8QsNz46zWFHxOBMyregoJcEGq1KoSJfwyz0vQ0WDDKhK0DL97Vsjo1OLl5ttWLb/cqdswfO6xMueNq2tP0W/65T8721tUBIQh0PdgE9L7V/IfM/CyeYPyEf6TQRf3GJy1CyvE8ddUSul+jPMo3QOnYtG3mZcwcemV94XACA8rJjMcEN7T4RKGykcPJV9Be0TuhfhgRQB634P6jI4O6VR5ITd2y1EKwIbg6LCkN55pJUg04NfROJ8WfgRLi8VdFwV/j7r6L49BeiCgu"
  #myTOrpassword"
graphite:
  host: "graphHost"
  port: "8092"
  report:
    schedule: "re"
  enable: "true"
