server:
  port: 8000
cassandra:
  hostnames: "myOrHost"
  username: "myOrUser"
  password: "myOrPassword"

---
spring:
  profiles: dev
cassandra:
  hostnames: "myDOrHost"
  username: "myDOrUser"
  password: "myDOrpassword"
---
spring:
  profiles: test
cassandra:
  hostnames: "myTOrHost"
  username: "myTOrUser"
  password: "myTOrpassword"
graphite:
  host: "graphHost"
  port: "8092"
  report:
    schedule: "re"
  enable: "true"

cassandra.password=AgBKmdsXAeoMnC5LqAGZe6KVWXwQ5YbRvZGmnCqpjf3Cko7G1BCcLZjzhKye7SH7/EXg/g96t+P+r2ExAigccpaNvHzsSA6kJQWo7LsP+csa4gx+h180AT0mcejGHJ1NmxGTICqMGaNYwLbcSQIgQuCxxpzdhC0BT/E7xscRDGkQ6rmi7TccBXoZ+sKZYsUUzmgyCnyYeKDsmp4ALhhZ9B+qLTg/IH45uoYqyMEoGWQS1vptanLY20vpfv44r19qgvtdVYxnUWgmPob/9T92eVWQC72n5irpD8YwfJsgkX9CuBePLwyVkYr0sJHztEnNAMBDVoOlULeldaaRUEmJRmWTDLfiphUteFNBQisTbV86lZXyT91uAXZROQHfg25RjqVTpNjh6bL9M8c9yVF5apdS/LUlGMg+eLQoVYxa5nRuANNz6HCj6CZgS5+excBVCQqZ2nlHvxs77LNvL7OMe8QfFQMIiXhZyfjWs39mjiOPojzu66C/Z+d/KxwGv0Wdf6M37dKte8xMeT7Ib6UhYe4mVzoJovA4gC04qAtEx8C+q5OtVJ5H6iMmjkvj1dmQhUzRPmfx4E72617+iqWa7BcMj8GlpK0Zm2BSu2IVEgBRZxtqxQdcGVCJzqWa/Y3XzRD7XPlkUrUXv42LkbAxzdz1opjMVhAL53KQ9W5Cx2jBlraEJtMlbNmK0EVngkYR/VHh2EvTk7+Wa1Dc7bzIUxzI
