server:
  port: 8000
cassandra:
  hostnames: "myOrHost"
  username: "myOrUser"
  password: "myOrPassword"

---
spring:
  profiles: dev
cassandra:
  hostnames: "myDOrHost"
  username: "myDOrUser"
  password: "myDOrpassword"
---
spring:
  profiles: test
cassandra:
  hostnames: "myTOrHost"
  username: "myTOrUser"
  password: "{cipher}15826AgBraLFB4qyOp3FQqeicgUhlZYRm433bleMKUQTzmdvCiZdvFlx5U4kQMhynMcE0aGt5cAUnFG3ulMpBN6fmSbQQVMbgs1W45rVW91IxP0h6eE40tVyF71214i9A/qOC4UNnKICd1IWA63uHM/FeGoAh21D9Zo5ZjFAXUKdMQ7eO8LvhwzvZPzaNP0VjtnFrgTxwwkLipMD7DKGPGoc45B7/1HT9Vk0OjEVOKcwViurwKbaViTn8y1kl2mXlPUwWgWSpc+OS8KJFi5QvbBSYvssrVKXXr/MUXcWoAImRXXKm7UJjeiTwnZIAuKQSRJ62Js2u56/JZsKT3M3y8Y+n8JpUrs5F5OdkeI/I4WFXOEsuaJ7k8Le4J0qO1LQh4gZB6W2XwAwkkCE61maWbtuTtfE1sGX3MvxunitbrBLp17s6/vpSvAzgKwLDZJM6CEjlG3DNFEsFnNoqG+fJd+cpdKa2nuJ/wmwINfKdheJ9NgcpEJ1+s3c6oV+Kj0Ki8m55VnL/4Hp/Ny4omohHKjjtAAi/0m4iYXa/qVOiFRNhxOuscQOmDxQ23LmWfUss124MG79b/EKUjAe4DcVsb8EmjPF7KEme4xzdPTFkJBYx2mP/+07/oA+0tcvUGYpwd8u3KRhJ+0p9XErk4tNsVJSFnwb7QMoroY2pnRqA+6JkO1aX0E9coRQI3jo5q4YjUzXt3Mn71FGH1whhWDJcDzul6JZn"
  #myTOrpassword"
graphite:
  host: "graphHost"
  port: "8092"
  report:
    schedule: "re"
  enable: "true"

#cassandra.password=AgBKmdsXAeoMnC5LqAGZe6KVWXwQ5YbRvZGmnCqpjf3Cko7G1BCcLZjzhKye7SH7/EXg/g96t+P+r2ExAigccpaNvHzsSA6kJQWo7LsP+csa4gx+h180AT0mcejGHJ1NmxGTICqMGaNYwLbcSQIgQuCxxpzdhC0BT/E7xscRDGkQ6rmi7TccBXoZ+sKZYsUUzmgyCnyYeKDsmp4ALhhZ9B+qLTg/IH45uoYqyMEoGWQS1vptanLY20vpfv44r19qgvtdVYxnUWgmPob/9T92eVWQC72n5irpD8YwfJsgkX9CuBePLwyVkYr0sJHztEnNAMBDVoOlULeldaaRUEmJRmWTDLfiphUteFNBQisTbV86lZXyT91uAXZROQHfg25RjqVTpNjh6bL9M8c9yVF5apdS/LUlGMg+eLQoVYxa5nRuANNz6HCj6CZgS5+excBVCQqZ2nlHvxs77LNvL7OMe8QfFQMIiXhZyfjWs39mjiOPojzu66C/Z+d/KxwGv0Wdf6M37dKte8xMeT7Ib6UhYe4mVzoJovA4gC04qAtEx8C+q5OtVJ5H6iMmjkvj1dmQhUzRPmfx4E72617+iqWa7BcMj8GlpK0Zm2BSu2IVEgBRZxtqxQdcGVCJzqWa/Y3XzRD7XPlkUrUXv42LkbAxzdz1opjMVhAL53KQ9W5Cx2jBlraEJtMlbNmK0EVngkYR/VHh2EvTk7+Wa1Dc7bzIUxzI
